### ISSUE TITLE
Problem compiling 20141118

### ISSUE THREAD

**Issue by paulbilkis** [pioneerspacesim/pioneer#3931]
So, my video card does not support OpenGL version > 2.1, and as I understood I needed the last pioneer build with OpenGL 2.1 - 20141118
I cloned it, then checkout 20141118. 
Then I ran:
```
sudo ./bootstrap
sudo ./configure
sudo make
```
It failed on some point:
```
Making all in text
make[2]: вход в каталог «/media/bilqis/bilqis/debs/pioneer/src/text»
  CXX      TextureFont.o
TextureFont.cpp: In member function ‘Text::TextureFont::Glyph Text::TextureFont::BakeGlyph(Uint32)’:
TextureFont.cpp:365:77: error: no matching function for call to ‘max(int&, unsigned int&)’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);
                                                                             ^
TextureFont.cpp:365:77: note: candidates are:
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:365:77: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);
                                                                             ^
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:365:77: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);
                                                                             ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:365:77: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);
                                                                             ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:365:77: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);
                                                                             ^
TextureFont.cpp:430:71: error: no matching function for call to ‘max(int&, unsigned int&)’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);
                                                                       ^
TextureFont.cpp:430:71: note: candidates are:
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:430:71: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);
                                                                       ^
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:430:71: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);
                                                                       ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:430:71: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);
                                                                       ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:430:71: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);
                                                                       ^
Makefile:373: ошибка выполнения рецепта для цели «TextureFont.o»
make[2]: *** [TextureFont.o] Ошибка 1
make[2]: выход из каталога «/media/bilqis/bilqis/debs/pioneer/src/text»
Makefile:1430: ошибка выполнения рецепта для цели «all-recursive»
make[1]: *** [all-recursive] Ошибка 1
make[1]: выход из каталога «/media/bilqis/bilqis/debs/pioneer/src»
Makefile:398: ошибка выполнения рецепта для цели «all-recursive»
make: *** [all-recursive] Ошибка 1

```
My OS is Debian 8. Pioneer version is 20141118.

```
bilkis@bilkis:/media/bilqis/bilqis/debs/pioneer$ uname -a
Linux bilkis 3.16.0-4-686-pae #1 SMP Debian 3.16.39-1 (2016-12-30) i686 GNU/Linux
bilkis@bilkis:/media/bilqis/bilqis/debs/pioneer$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
bilkis@bilkis:/media/bilqis/bilqis/debs/pioneer$ glxinfo | grep "OpenGL version"
OpenGL version string: 2.1 Mesa 10.3.2

```

Tell me, if you need any additional information.

**Comment by impaktor** [comment]
Looks like something is up with TextureFont, might have been some incompatible changes since 2014, so the version you have installed no longer is compatible to the 2017/Debian 8 version?

I'm sure others know these things better than me.

**Comment by paulbilkis** [comment]
You're probably right. But the thing is, I have pretty old video card
which doest not support modern OpenGL.

04:00.0 VGA compatible controller: Advanced Micro Devices, Inc.
[AMD/ATI] RV370 [Radeon X300/X550/X1050 Series]

So, I'm wondering, what should I do to play pioneer? If I find old
binaries of pioneer for linux, will it work?

**Comment by impaktor** [comment]
I think this should be solvable, on your end. Just figure out how/why Texture thingy isn't compiling.

A silly idea, but should work, is installing an older Debian version, possibly in virtual box, and build and play it thorough that.

**Comment by fluffyfreak** [comment]
@paulbilkis open up the file `TextureFont.cpp` and replace:
`m_atlasVIncrement = std::max(m_atlasVIncrement, bmStrokeGlyph->bitmap.rows);`
with
`m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));`

and 

`m_atlasVIncrement = std::max(m_atlasVIncrement, bmGlyph->bitmap.rows);`
with
`m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));`

That should fix that error

**Comment by paulbilkis** [comment]
@fluffyfreak I replaced it, but still I'm getting this error:

```
make[2]: вход в каталог «/media/bilqis/bilqis/debs/pioneer/src/text»
  CXX      TextureFont.o
TextureFont.cpp: In member function ‘Text::TextureFont::Glyph Text::TextureFont::BakeGlyph(Uint32)’:
TextureFont.cpp:366:104: error: no matching function for call to ‘max(int&, unsigned int)’
   m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));
                                                                                                        ^
TextureFont.cpp:366:104: note: candidates are:
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:366:104: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));
                                                                                                        ^
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:366:104: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
   m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));
                                                                                                        ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:366:104: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));
                                                                                                        ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:366:104: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
   m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmStrokeGlyph->bitmap.rows));
                                                                                                        ^
TextureFont.cpp:432:105: error: no matching function for call to ‘max(int&, unsigned int)’
          m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));
                                                                                                         ^
TextureFont.cpp:432:105: note: candidates are:
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note: template<class _Tp> const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:217:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:432:105: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
          m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));
                                                                                                         ^
In file included from /usr/include/c++/4.9/list:60:0,
                 from /usr/include/sigc++-2.0/sigc++/signal.h:7,
                 from /usr/include/sigc++-2.0/sigc++/sigc++.h:86,
                 from ./../libs.h:11,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note: template<class _Tp, class _Compare> const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algobase.h:261:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:432:105: note:   deduced conflicting types for parameter ‘const _Tp’ (‘int’ and ‘unsigned int’)
          m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));
                                                                                                         ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note: template<class _Tp> _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3449:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:432:105: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
          m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));
                                                                                                         ^
In file included from /usr/include/c++/4.9/algorithm:62:0,
                 from ./../libs.h:25,
                 from TextureFont.h:7,
                 from TextureFont.cpp:4:
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note: template<class _Tp, class _Compare> _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/4.9/bits/stl_algo.h:3454:5: note:   template argument deduction/substitution failed:
TextureFont.cpp:432:105: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘int’
          m_atlasVIncrement = std::max(m_atlasVIncrement, static_cast<unsigned int>(bmGlyph->bitmap.rows));
                                                                                                         ^
Makefile:373: ошибка выполнения рецепта для цели «TextureFont.o»
make[2]: *** [TextureFont.o] Ошибка 1
make[2]: выход из каталога «/media/bilqis/bilqis/debs/pioneer/src/text»
Makefile:1430: ошибка выполнения рецепта для цели «all-recursive»
make[1]: *** [all-recursive] Ошибка 1
make[1]: выход из каталога «/media/bilqis/bilqis/debs/pioneer/src»
Makefile:398: ошибка выполнения рецепта для цели «all-recursive»
make: *** [all-recursive] Ошибка 1

```

**Comment by laarmen** [comment]
Hi,

You might want to try a compiled version, see https://sourceforge.net/projects/pioneerspacesim/files/

**Comment by fluffyfreak** [comment]
There is no compiled version from 2014.

@paulbilkis the problem is that `std::max(m_atlasVIncrement` is being compared to a different type of variable. So last thing to try is changing those two from:
`m_atlasVIncrement = std::max(m_atlasVIncrement, `
to
`m_atlasVIncrement = std::max(static_cast<unsigned int>(m_atlasVIncrement), `

I am currently working on getting openGL 2.1 support into the game with PR #3934 if you can wait for that to be finished and working.

**Comment by paulbilkis** [comment]
@fluffyfreak that's a great thing you're doing.
With latest fix it finally compiled.
But I'm getting this error when launching. It starts to generate universe, gets to 11 billion years and crush with error:
```
bilkis@bilkis:/media/bilqis/bilqis/debs/pioneer$ ./src/pioneer
ver git (92c64ad) on: Linux

System Name: Linux
Host Name: bilkis
Release(Kernel) Version: 3.16.0-4-686-pae
Kernel Build Timestamp: #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22)
Machine Arch: i686
Domain Name: (none)

SDL Version 2.0.2
Initialized GL2 renderer
invalid axis binding '' in config file for BindAxisPitch
invalid axis binding '' in config file for BindAxisRoll
invalid axis binding '' in config file for BindAxisYaw
started 1 worker threads
Creating new galaxy generator 'legacy' version 1
Number of factions added: 103
StarSystemCache: misses: 2227, slave hits: 0, master hits: 0
SectorCache: misses: 1571, slave hits: 0, master hits: 11138
Face Generation source images loaded.
error: OpenGL error(s) during frame:
GL_INVALID_VALUE

```

**Comment by fluffyfreak** [comment]
Hmm, at this point @paulbilkis I think you might be better off waiting until we've got a modern version that works with Pioneer. There's likely to be more problems like this.

If you're determined to try then you need to find the method `RendererGL2::SwapBuffers()` in file `src\graphics\RendererGL2.cpp` and comment out the block of code from lines 142 to 162. This might let it limp on but it sounds like some of the rendering might be corrupted.

**Comment by paulbilkis** [comment]
@fluffyfreak you're probably right. I fixed that error, but now I'm getting segmentation fault.
So, I'll just wait 'till you get the modern pioneer to work with OpenGL 2.1.
Thank you for your support and your work.

**Comment by impaktor** [comment]
@paulbilkis could you please try building (and running) #3934 
```
git checkout -b fluffyfreak-glew-gl2 master
git pull https://github.com/fluffyfreak/pioneer.git glew-gl2
```

**Comment by fluffyfreak** [comment]
@paulbilkis opengl 2.1 is now available in the main/master branch if you want to build it yourself.
