### ISSUE TITLE
Build failure with USE_SYSTEM_LIBLUA

### ISSUE THREAD

**Issue by orbea** [pioneerspacesim/pioneer#4939]
### Observed behaviour

The build with `-DUSE_SYSTEM_LIBLUA=ON` fails.

```
[16/432] Building CXX object contrib/imgui/CMakeFiles/imgui.dir/examples/imgui_impl_opengl3.cpp.o
samu: job failed: /usr/local/bin/clang++  -DFMT_LOCALE -DGLEW_STATIC -I. -I/tmp/pioneer -I/usr/include/lua5.2 -I/tmp/pioneer/src -I/tmp/pioneer/contrib -I/tmp/pioneer/contrib/fmt/include -I/usr/include/assimp -I/usr/include/freetype2 -I/usr/include/SDL2 -I/usr/include/sigc++-2.0 -I/usr/lib64/sigc++-2.0/include -I/tmp/pioneer/contrib/glew -O2 -g -DNDEBUG   -std=gnu++11 -MD -MT CMakeFiles/pioneer.dir/src/main.cpp.o -MF CMakeFiles/pioneer.dir/src/main.cpp.o.d -o CMakeFiles/pioneer.dir/src/main.cpp.o -c /tmp/pioneer/src/main.cpp
In file included from /tmp/pioneer/src/main.cpp:5:
In file included from /tmp/pioneer/src/ModelViewer.h:18:
In file included from /tmp/pioneer/src/ui/Context.h:45:
In file included from /tmp/pioneer/src/ui/Lua.h:8:
In file included from /tmp/pioneer/src/lua/LuaObject.h:9:
/tmp/pioneer/src/lua/LuaMetaType.h:11:10: fatal error: 'src/lua.h' file not found
#include "src/lua.h"
         ^~~~~~~~~~~
1 error generated.
samu: subcommand failed
```

### Expected behaviour

The build with `-DUSE_SYSTEM_LIBLUA=ON` should work.

### Steps to reproduce

Build pioneer with `-DUSE_SYSTEM_LIBLUA=ON` and lua52 installed system wide.

I bisected this.
```
e80d11ee18165127c8710c3bd17acb168726075a is the first bad commit
commit e80d11ee18165127c8710c3bd17acb168726075a
Author: Webster Sheets <webster@web-eworks.com>
Date:   Sat May 9 05:48:42 2020 -0400

    LuaMetaType + LuaObject 2.0
    
    Add a new system to bind member functions and data types to lua without
    requiring the programmer to spend a whole day writing boilerplate to
    pull arguments and data out of lua.
    
    Replace our existing '__attribute_x' system for attrs with a separate
    'attrs' table, (slightly) simplifying lookup. Support attribute setters
    via a __newindex metamethod (attribute handlers will be called with an
    extra parameter corresponding to the setter).
    
    Don't lean on luaL_newmetatable anymore, explicitly store metatypes in
    the registry table LuaMetaTypes for better namespacing and reliable
    lookup.

 src/lua/Lua.cpp         |   3 +-
 src/lua/LuaCall.h       | 103 +++++++++
 src/lua/LuaConsole.cpp  |   4 +-
 src/lua/LuaMetaType.cpp | 448 +++++++++++++++++++++++++++++++++++++
 src/lua/LuaMetaType.h   | 409 ++++++++++++++++++++++++++++++++++
 src/lua/LuaObject.cpp   | 577 +++++++++++++++++-------------------------------
 src/lua/LuaObject.h     |  52 ++---
 src/lua/LuaPushPull.h   |   1 +
 8 files changed, 1185 insertions(+), 412 deletions(-)
 create mode 100644 src/lua/LuaCall.h
 create mode 100644 src/lua/LuaMetaType.cpp
 create mode 100644 src/lua/LuaMetaType.h
```
e80d11ee18165127c8710c3bd17acb168726075a

__My pioneer version (and OS):__

OS: `Slackware64-current`
pioneer: https://github.com/pioneerspacesim/pioneer/commit/f34619f28220b57abd39fea0ad43869ee4aa9429
lua: `5.2.4`
