### ISSUE TITLE
Error while compiling - pioneer/pioneer-thirdparty/source/sdl2/src/dynapi/SDL_dynapi.c:237: undefined reference to `dlopen'

### ISSUE THREAD

**Issue by CmdrBugbear** [pioneerspacesim/pioneer#5098]
### Observed behaviour / Steps to reproduce
Fresh build on a newly installed Ubuntu 20.04.
Building pioneer from git snapshot: 

commit c5c9f1f62f2228e98e9b5bae47ed686502d9d687 (HEAD -> master, tag: 20201222-rc1, origin/master, origin/HEAD)
Author: Webster Sheets <Web-eWorks@users.noreply.github.com>
Date:   Tue Dec 22 03:57:13 2020 -0500

Installed prerequisites (replaced libsigc++-2.0 with libsigc++-2.0-0v5

Building pioneer-thirdparty from git snapshot:

commit f0335969f17b1f143d0ed956d6c0214ce7716138 (HEAD -> master, origin/master, origin/HEAD)
Merge: 53949308 35f0d5be
Author: Andrew Copland <fluffyfreak@users.noreply.github.com>
Date:   Fri Nov 27 23:25:46 2020 +0000

./bootstrap thirdparty
make -C build -j8

### Expected behaviour
Application compiles successfully

__My pioneer version (and OS):__
(See git snapshot version above)
Ubuntu 20.04

**Comment by The-EG** [comment]
You shouldn't need to build pioneer-thirdparty on Linux, it's more straight forward to install the appropriate *-dev packages from your distributions package manager and build just pioneer. See [COMPILING](https://github.com/pioneerspacesim/pioneer/blob/master/COMPILING.txt#L42).

Currently, the libraries in pioneer-thirdparty are provided mainly as precompiled dependencies for the windows build.

**Comment by CmdrBugbear** [comment]
Ah.  Crisis averted!

I deleted the build directory, ran the following commands:

./bootstrap
make -C build -j8
./pioneer

Back up and running!!!
